### ISSUE TITLE
A question regarding the normalisation

### ISSUE THREAD

**Issue by dmfolgado** [Bartvelp/edge_tpu_MNIST#1]
Hi, thanks for sharing this example. I was wondering if I am missing something regarding the normalisation. When you train the model you convert the MNIST from uint8 to float by dividing for 255. However, in the inference step you use the input to the model as uint8 (which I understand being due EdgeTPU on Coral constrains). However, it seems the model that was trained using floats is being feed now with uint8. How does the model become aware of this? It is during the post-quantization step that in some way a model that was trained using floats between 0 and 1 will be ready to receive uint8?

Thanks

**Comment by Bartvelp** [comment]
Hi
Yes that is exactly the case. As I understand [these lines](https://github.com/Bartvelp/edge_tpu_MNIST/blob/2f0eb4bffc9eb24c517969e64b12f41eec7570a3/perform_post_training_quant.py#L30-L31) dictate that the new input and output should be 8-bit intigers.
By then passing some float input data using the `representative_dataset_gen` function tensorflow can figure out the range that the integers need to represent.

**Comment by dmfolgado** [comment]
Alright! Wondering the same thing but glad I can confirm with someone else. Starts to make sense!
